### ISSUE TITLE
TimeSpanConverter throws OverflowException.

### ISSUE THREAD

**Issue by Niewiarowski** [angelobreuer/Lavalink4NET#10] opened 2019-07-08 12:16 UTC
https://github.com/angelobreuer/Lavalink4NET/blob/master/src/Lavalink4NET/Util/TimeSpanConverter.cs#L24

Throws an OverflowException when you try to search for some streams. 
Searching for https://listen.moe/stream will cause this to happen.

**Comment by angelobreuer** [comment] 2019-07-08 17:07
https://github.com/angelobreuer/Lavalink4NET/commit/7115c3bbc4ff38ecb9360c11975143c66eeb5d41 I hope the issue is fixed now .. thanks for reporting 😊

**Closed** 2019-07-08 18:04 UTC
Labels: bug
