### ISSUE TITLE
Set the player State to NotPlaying when a track ends

### ISSUE THREAD

**Issue by FenikkusuNeko** [angelobreuer/Lavalink4NET#16] opened 2019-09-07 19:51 UTC
Set the player State to NotPlaying when a track ends.
In this case it's easier to check when to pause, to play or to add to queue a new track while the player is currently playing.

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:05
Actually, I now see that this is not possible at all because the track events are async tasks instead of event methods.
So, on overriding the track end event, if the player state is set on this event, the base method have to be called.

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:07
You should use events instead of tasks. Invoke them and we can assign them to our event tasks.

**Comment by angelobreuer** [comment] 2019-09-07 21:12
There is a track end event in the node implementation: https://github.com/angelobreuer/Lavalink4NET/blob/master/src/Lavalink4NET/LavalinkNode.cs#L90

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:16
I see.
Now either I use the events in the service and control the player for that event is
or, wouldn't be nice to have events in the player as well?

**Comment by angelobreuer** [comment] 2019-09-07 21:19
Would the above commit resolve the problem?

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:21
Yes, I wanted to set the State but has a private setter.
Now, I just have to take care and call the base method then to do the other things.

**Comment by angelobreuer** [comment] 2019-09-07 21:24
Which base method do you mean?

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:25
When overriding the TrackEndEvent from the Player class.

**Comment by angelobreuer** [comment] 2019-09-07 21:30
Are you overriding the QueuedLavalinkPlayer or the LavalinkPlayer class, because the LavalinkPlayer class simply sets the state to NotPlaying (in f58c9905eeaf199cf7067d706593b02e17de2f9b, assuming disconnect on stop is disabled). So you just need to call the base method and then the state will be set to NotPlaying.

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:32
Sorry for confusion.
Yes, if I want to override the track end event from LavalinkPlayer class I have to call the base in order for the State to be set to NotPlaying.

**Comment by angelobreuer** [comment] 2019-09-07 21:40
I assume your code looks like the following: 

```csharp
/// <summary>
///     Asynchronously triggered when a track ends.
/// </summary>
/// <remarks>
///     When overriding this method without supering / base calling it, the disconnect on
///     stop function will be prevent.
/// </remarks>
/// <param name="eventArgs">the track event arguments</param>
/// <returns>a task that represents the asynchronous operation</returns>
public override async Task OnTrackEndAsync(TrackEndEventArgs eventArgs)
{
    // Assert: State == PlayerState.Playing

    // the following will set the State to NotPlaying
    await base.OnTrackEndAsync(eventArgs);

    // Assert: State == PlayerState.NotPlaying

    // do whatever
}
```

The patch f58c990 should solve the problem because it simply sets the state to `NotPlaying`.
But I have not found any method in `LavalinkPlayer` that explicitly requires the `NotPlaying` state.

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:42
Well, for example:
- when I pause, I first check if anything is playing, then check if the player is paused
- when I resume, the same thing
- but, when I add a new track, with NotPlaying I can make the player to play the track immediately or to add the track in the queue.

**Comment by angelobreuer** [comment] 2019-09-07 21:47
The QueuedLavalinkPlayer also checks for the NotPlaying state and then decides whether to player the track immediately or to add the track in the queue (https://github.com/angelobreuer/Lavalink4NET/blob/f58c9905eeaf199cf7067d706593b02e17de2f9b/src/Lavalink4NET/Player/QueuedLavalinkPlayer.cs#L124-L144)

**Comment by FenikkusuNeko** [comment] 2019-09-07 21:49
Ok, but how should that work when the NotPlaying state is set **only** when the player gets connected.
That's why I opened this issue, I checked if the NotPlaying state is set when the track ends.

**Comment by angelobreuer** [comment] 2019-09-07 21:57
I have to admit, I'm just wondering why that works .. I will debug that through, but then f58c9905eeaf199cf7067d706593b02e17de2f9b should solve the problem.

**Comment by angelobreuer** [comment] 2019-09-07 22:12
Yep, the QueuedLavalinkPlayer disconnects when the queue is empty (assuming disconnect on stop is enabled), the problem did not come up, because the stop sets the actual player state to NotConnected. (see: [LavalinkPlayer.cs@L166](https://github.com/angelobreuer/Lavalink4NET/blob/f58c9905eeaf199cf7067d706593b02e17de2f9b/src/Lavalink4NET/Player/LavalinkPlayer.cs#L166)). So f58c990 solves your issue.

I will make an additional fix for the QueuedLavalinkPlayer to correct the behavior when disconnect on stop is disabled (but this is not related to your issue).

**Comment by FenikkusuNeko** [comment] 2019-09-07 23:06
Will you apply the patch and push to NuGet?

**Comment by angelobreuer** [comment] 2019-09-07 23:27
Build is building / deploying: [AppVeyor CI Build - 27256577](https://ci.appveyor.com/project/angelobreuer/lavalink4net/builds/27256577)
😊 Hope the issue is fixed now — thanks for reporting!

**Closed** 2019-09-07 23:58 UTC
Labels: bug
